### ISSUE TITLE
import_undici.setGlobalDispatcher is not a function.

### ISSUE THREAD

**Issue by MeewMeew** [retrouser955/discord-player-youtubei#24]
### Before you report a bug ...
- [x] I have checked that I am on the latest version of discord-player-youtubei
- [x] I have checked existing issues to see if this is a duplicate report

### Description of the bug

- I register this extractor but got error:

```plaintext
27581 | var meta_url = import_meta.url;
27582 | var is_cjs = !meta_url;
27583 | var __dirname__ = is_cjs ? __dirname : import_path.default.dirname((0, import_url.fileURLToPath)(meta_url));
27584 | var { homepage, version, bugs } = { "homepage": "https://github.com/LuanRT/YouTube.js#readme", "version": "10.5.0", "bugs": { "url": "https://github.com/LuanRT/YouTube.js/issues" } };
27585 | var repo_url = homepage == null ? void 0 : homepage.split("#")[0];
27586 | (0, import_undici.setGlobalDispatcher)(new import_undici.Agent({
                          ^
TypeError: import_undici.setGlobalDispatcher is not a function. (In 'import_undici.setGlobalDispatcher(new import_undici.Agent({
    connect: {
      timeout: 60000
    }
  }))', 'import_undici.setGlobalDispatcher' is undefined)
      at E:\disbot-v2\node_modules\youtubei.js\bundle\node.cjs:27586:19
      at E:\disbot-v2\node_modules\discord-player-youtubei\dist\index.js:45:24
```

- Here is my code:

```ts
  await player.extractors.register(YoutubeiExtractor, {
    authentication: oauthTokens,
    streamOptions: {
      useClient: "ANDROID",
    },
  });
```

### Steps to reproduce

Just do like previous step

### Versioning
discord-player: 6.7.1
node.js: latest

**Comment by retrouser955** [comment]
I have only tested the extractor on NodeJS LTS and haven't on the latest. This seems to be related to undici being undefined.

**Comment by retrouser955** [comment]
Could you try running the command `npm install undici` and see if that fixes it

**Comment by retrouser955** [comment]
I am closing this issue due to inactivity. Will reopen if needed.
