### ISSUE TITLE
When add playlist

### ISSUE THREAD

**Issue by EbookTechPL** [retrouser955/discord-player-youtubei#26]
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ContentMetadataView!
    at ERROR_HANDLER (…/node_modules/youtubei.js/bundle/node.cjs:14521:32)
    at Object.parseItem (…/node_modules/youtubei.js/bundle/node.cjs:14885:7)
    at new PageHeaderView (…/node_modules/youtubei.js/bundle/node.cjs:11495:36)
    at Object.parseItem (…/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at new PageHeader (…/node_modules/youtubei.js/bundle/node.cjs:11511:35)
    at parseItem (…/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at parse (…/node_modules/youtubei.js/bundle/node.cjs:14929:32)
    at Object.parseResponse (…/node_modules/youtubei.js/bundle/node.cjs:14674:32)
    at new Feed (…/node_modules/youtubei.js/bundle/node.cjs:15130:83)
    at new Playlist (…/node_modules/youtubei.js/bundle/node.cjs:15919:5)

### Versioning
discord-player: 6.7.1
node.js: 22.9.0
discord-player-youtubei: 1.3.3-beta.2

**Comment by retrouser955** [comment]
Do you have metadata missing? If not, please ignore.
