### ISSUE TITLE
Search result not populating any tracks

### ISSUE THREAD

**Issue by jay194** [retrouser955/discord-player-youtubei#30]
### Before you report a bug ...
- [x] I have checked that I am on the latest version of discord-player-youtubei
- [x] I have checked existing issues to see if this is a duplicate report

### Description of the bug
I believe search is not using extractor, even though it is registered.

Registering bot:
```
const player = new Player(client);
player.extractors.register(YoutubeiExtractor, {
	authentication: authToken
})
```

```
Extractor context (I think this means its registered):
  store: Collection(1) [Map] {
    'com.retrouser955.discord-player.discord-player-youtubei' => _YoutubeiExtractor {
      context: [Circular *2],
      options: [Object],
      priority: 2,
      protocols: [Array],
      createBridgeQuery: [Function: createBridgeQuery],
      innerTube: Innertube {},
      _stream: [Function (anonymous)]
    }
  },
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
```

Searching for song:
```
  const player = useMainPlayer()

  let song = inter.options.getString('song');

  const res = await player.search(song, {
      requestedBy: inter.member,
      searchEngine: QueryType.YOUTUBE
  });
```

Data from search:
```
  _data: {
    query: 'cbat',
    queryType: 'youtube',
    requestedBy: User {
      id: '188749513924673536',
      bot: false,
      system: false,
      flags: [UserFlagsBitField],
      username: 'jay195',
      globalName: 'jay195',
      discriminator: '0',
      avatar: 'c5025d08bdc2ec557c0219a1a1d50bb9',
      banner: undefined,
      accentColor: undefined,
      avatarDecoration: null
    },
    extractor: undefined
  }
```

### Steps to reproduce

Restart bot
Play command: /play Allstar
No song played and error

```
TypeError: Cannot read properties of undefined (reading 'title')
    at Object.execute (C:\dev\Discord bots\NotMusicBot\commands\music\play.js:38:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (C:\dev\Discord bots\NotMusicBot\events\interactionCreate.js:16:4)
```

### Versioning
    "@discord-player/extractor": "^4.5.1",
    "discord-player": "^6.7.1",
    "discord-player-youtubei": "^1.3.5",
    "discord.js": "^14.14.1",
    "ffmpeg-static": "^5.2.0",

**Comment by jay194** [comment]
Could be something else. All I know is search result is now empty after Nov 12th, for some reason.

**Comment by jay194** [comment]
Logs of search result for "Cbat". Working prior to Nov 12th

```
SearchResult {
  player: <ref *1> Player {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    requiredEvents: [ 'error' ],
    id: '1306402655492378624',
    nodes: GuildNodeManager {
      player: [Circular *1],
      cache: Collection(0) [Map] {}
    },
    voiceUtils: VoiceUtils { player: [Circular *1], cache: Collection(0) [Map] {} },
    extractors: ExtractorExecutionContext {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      requiredEvents: [Array],
      player: [Circular *1],
      store: [Collection [Map]],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    events: PlayerEventsEmitter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      requiredEvents: [Array],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    routePlanner: null,
    version: '6.7.1',
    lyrics: LrcLib {
      player: [Circular *1],
      api: 'https://lrclib.net/api',
      timeout: 15000,
      bucket: [SequentialBucket]
    },
    client: Client {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: 11,
      options: [Object],
      rest: [REST],
      ws: [WebSocketManager],
      actions: [ActionsManager],
      voice: [ClientVoiceManager],
      shard: null,
      users: UserManager {},
      guilds: GuildManager {},
      channels: ChannelManager {},
      sweepers: [Sweepers],
      presence: [ClientPresence],
      user: [ClientUser],
      application: [ClientApplication],
      readyTimestamp: 1731541065680,
      commands: [Collection [Map]],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: true
    },
    options: {
      lockVoiceStateHandler: false,
      blockExtractors: [],
      blockStreamFrom: [],
      connectionTimeout: 20000,
      lagMonitor: 30000,
      queryCache: [QueryCache],
      useLegacyFFmpeg: false,
      skipFFmpeg: true,
      probeTimeout: 5000,
      ytdlOptions: [Object]
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  _data: {
    query: 'cbat',
    queryType: 'youtube',
    requestedBy: User {
      id: '188749513924673536',
      bot: false,
      system: false,
      flags: [UserFlagsBitField],
      username: 'jay195',
      globalName: 'jay195',
      discriminator: '0',
      avatar: 'c5025d08bdc2ec557c0219a1a1d50bb9',
      banner: undefined,
      accentColor: undefined,
      avatarDecoration: null
    },
    extractor: undefined
  }
}
```

**Comment by IziPeezeLemonSqueeze** [comment]
same problem, until last night it was working

```
  _data: {
    query: 'https://www.youtube.com/watch?v=KleqhDUtgwg',
    queryType: 'youtube',
    requestedBy: undefined,
    extractor: undefined
  }
```

**Comment by IziPeezeLemonSqueeze** [comment]
> Please try without an oauth token. Youtube seems to be changing how TV OAuth is processed. Thanks!

I confirm that removing the token from the extractor makes the search work again
```
player.extractors.register(YoutubeiExtractor, {
	//authentication: config.YOUTUBE_TOKEN
})
```

**Comment by jay194** [comment]
works for now in my local, but not when I deploy to ec2 instance.

```
} ERR_NO_RESULT [Error]: [Object] Could not extract stream for this track

Error: Streaming data not available
    at Object.chooseFormat (/home/ec2-user/NotMusicBot/node_modules/youtubei.js/bundle/node.cjs:1921:11)
    at VideoInfo.chooseFormat (/home/ec2-user/NotMusicBot/node_modules/youtubei.js/bundle/node.cjs:14493:32)
    at streamFromYT (/home/ec2-user/NotMusicBot/node_modules/discord-player-youtubei/dist/index.js:195:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2983:12
    at async _ExtractorExecutionContext.run (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:1465:22)
    at async #createGenericStream (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2977:22)
    at async _GuildQueuePlayerNode.play (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2829:9)
    at async Object.execute (/home/ec2-user/NotMusicBot/commands/music/play.js:87:37)
    at async Object.execute (/home/ec2-user/NotMusicBot/events/interactionCreate.js:16:4)
    at Proxy.<anonymous> (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:331:25)
    at #throw (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2949:80)
    at _GuildQueuePlayerNode.play (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2845:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.execute (/home/ec2-user/NotMusicBot/commands/music/play.js:87:37)
    at async Object.execute (/home/ec2-user/NotMusicBot/events/interactionCreate.js:16:4) Track {
```

**Comment by Tarekthedeveloper** [comment]
> works for now in my local, but not when I deploy to ec2 instance.
> 
> ```
> } ERR_NO_RESULT [Error]: [Object] Could not extract stream for this track
> 
> Error: Streaming data not available
>     at Object.chooseFormat (/home/ec2-user/NotMusicBot/node_modules/youtubei.js/bundle/node.cjs:1921:11)
>     at VideoInfo.chooseFormat (/home/ec2-user/NotMusicBot/node_modules/youtubei.js/bundle/node.cjs:14493:32)
>     at streamFromYT (/home/ec2-user/NotMusicBot/node_modules/discord-player-youtubei/dist/index.js:195:35)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async /home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2983:12
>     at async _ExtractorExecutionContext.run (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:1465:22)
>     at async #createGenericStream (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2977:22)
>     at async _GuildQueuePlayerNode.play (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2829:9)
>     at async Object.execute (/home/ec2-user/NotMusicBot/commands/music/play.js:87:37)
>     at async Object.execute (/home/ec2-user/NotMusicBot/events/interactionCreate.js:16:4)
>     at Proxy.<anonymous> (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:331:25)
>     at #throw (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2949:80)
>     at _GuildQueuePlayerNode.play (/home/ec2-user/NotMusicBot/node_modules/discord-player/dist/index.js:2845:56)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Object.execute (/home/ec2-user/NotMusicBot/commands/music/play.js:87:37)
>     at async Object.execute (/home/ec2-user/NotMusicBot/events/interactionCreate.js:16:4) Track {
> ```

same error 
Anyone get a solution ? since there is no package update yet

**Comment by Tarekthedeveloper** [comment]
> Hey, sorry for late reply. I really need to get my schedule worked out. YouTube has mostly banned EC2 instances as they are known to be from data centers. I am looking into navigating around this but I'm afraid I have no solutions right now. You could try to use the PoToken and visitor data like the following.
> 
> ```ts
> const { poTokenExtraction } = require('discord-player-youtubei/experimental')
> 
> const ext = await register(..., {
>    ...options,
>    streamOptions: {
>       useClient: "WEB"
>    }
> })
> 
> const innertube = ext.innerTube
> 
> const token = await poTokenExtraction(innertube)
> 
> ext.setPoToken(token.poToken, innertube.session.context.client.visitorData)
> ```
> 
> EDIT: I have also pushed the ability to use proxies. You may try it by installing the nightly version directly from GitHub
> 
> ```ts
> const { ProxyAgent } = require('undici')
> await register(..., {
>    ...options,
>    agent: new ProxyAgent("https://.../...")
> })
> ```

 Sadly, same error ... is there any another solutions or package update ?

**Comment by retrouser955** [comment]
Seems YouTube hard banned EC2s. There are no ways around it I'm afraid.

**Comment by retrouser955** [comment]
I am closing this due to inactivity. Feel free to reopen.
